export interface Outfitter {
  id: string;
  name: string;
  location: string;
  province: string;
  country: string;
  lat: number;
  lng: number;
  species: string[];
  pricePerDay: number;
  rating: number;
  reviewCount: number;
  description: string;
  guide: string;
  guidePhoto: string;
  availability: string;
  maxGuests: number;
  featured: boolean;
  tags: string[];
}

export const OUTFITTERS: Outfitter[] = [
  {
    id: "1",
    name: "Glacier Peak Outfitters",
    location: "Glacier National Park Area",
    province: "Montana",
    country: "USA",
    lat: 48.7596,
    lng: -113.787,
    species: ["Elk", "Mule Deer", "Mountain Goat", "Bighorn Sheep"],
    pricePerDay: 650,
    rating: 4.9,
    reviewCount: 127,
    description: "Premier elk and mule deer hunting in the heart of the Rocky Mountains. 30+ years of guiding experience with 85%+ success rates.",
    guide: "Jake Harmon",
    guidePhoto: "JH",
    availability: "Sep–Nov",
    maxGuests: 6,
    featured: true,
    tags: ["Trophy", "Pack-in", "Tent Camp"],
  },
  {
    id: "2",
    name: "Last Frontier Guides",
    location: "Kenai Peninsula",
    province: "Alaska",
    country: "USA",
    lat: 60.5544,
    lng: -150.7847,
    species: ["Moose", "Brown Bear", "Black Bear", "Caribou", "Dall Sheep"],
    pricePerDay: 1200,
    rating: 4.8,
    reviewCount: 89,
    description: "Alaskan wilderness adventures for the serious trophy hunter. Float plane access to remote areas with unmatched big game populations.",
    guide: "Mike Valdez",
    guidePhoto: "MV",
    availability: "Aug–Oct",
    maxGuests: 4,
    featured: true,
    tags: ["Remote", "Float Plane", "Trophy"],
  },
  {
    id: "3",
    name: "Lone Star Trophy Hunts",
    location: "Hill Country",
    province: "Texas",
    country: "USA",
    lat: 30.2672,
    lng: -98.8597,
    species: ["Whitetail Deer", "Axis Deer", "Blackbuck", "Nilgai", "Wild Hog"],
    pricePerDay: 400,
    rating: 4.7,
    reviewCount: 203,
    description: "Texas Hill Country high-fence and free-range hunting on 10,000+ acres. Year-round access with diverse exotic and native species.",
    guide: "Buck Williams",
    guidePhoto: "BW",
    availability: "Year-round",
    maxGuests: 8,
    featured: true,
    tags: ["High-Fence", "Exotics", "Lodging"],
  },
  {
    id: "4",
    name: "Rockies Ridge Outfitters",
    location: "San Juan Mountains",
    province: "Colorado",
    country: "USA",
    lat: 37.8489,
    lng: -107.7761,
    species: ["Elk", "Mule Deer", "Black Bear"],
    pricePerDay: 550,
    rating: 4.6,
    reviewCount: 156,
    description: "World-class elk hunting in Colorado's legendary San Juan Mountains. Horseback and spike camp operations in prime wilderness units.",
    guide: "Tom Rivers",
    guidePhoto: "TR",
    availability: "Sep–Oct",
    maxGuests: 6,
    featured: false,
    tags: ["Horseback", "Wilderness", "Elk"],
  },
  {
    id: "5",
    name: "Prairie Wind Outfitters",
    location: "Cypress Hills",
    province: "Saskatchewan",
    country: "Canada",
    lat: 49.5,
    lng: -109.5,
    species: ["Whitetail Deer", "Mule Deer", "Antelope", "Coyote"],
    pricePerDay: 380,
    rating: 4.8,
    reviewCount: 94,
    description: "Saskatchewan's finest whitetail hunting. Giant genetics, agricultural land access, and professional guiding since 1995.",
    guide: "Dale Erickson",
    guidePhoto: "DE",
    availability: "Oct–Dec",
    maxGuests: 8,
    featured: true,
    tags: ["Whitetail", "Record Book", "Lodging"],
  },
  {
    id: "6",
    name: "Northern Shield Outfitters",
    location: "Lake Nipigon",
    province: "Ontario",
    country: "Canada",
    lat: 49.5,
    lng: -88.5,
    species: ["Moose", "Black Bear", "Woodland Caribou"],
    pricePerDay: 450,
    rating: 4.7,
    reviewCount: 71,
    description: "Remote Ontario wilderness camps accessible by floatplane. Trophy moose and bear in pristine boreal forest.",
    guide: "Chris Bouchard",
    guidePhoto: "CB",
    availability: "May–Oct",
    maxGuests: 6,
    featured: false,
    tags: ["Float Plane", "Remote", "Moose"],
  },
  {
    id: "7",
    name: "Wind River Trophy Hunts",
    location: "Wind River Range",
    province: "Wyoming",
    country: "USA",
    lat: 42.8,
    lng: -109.0,
    species: ["Elk", "Mule Deer", "Antelope", "Bighorn Sheep"],
    pricePerDay: 600,
    rating: 4.9,
    reviewCount: 112,
    description: "Wyoming's Wind River Range offers some of the most spectacular hunting in North America. Archery and rifle seasons available.",
    guide: "Seth Caldwell",
    guidePhoto: "SC",
    availability: "Sep–Nov",
    maxGuests: 4,
    featured: false,
    tags: ["Trophy", "Remote", "Archery"],
  },
  {
    id: "8",
    name: "BC Mountain Outfitters",
    location: "Kootenay Mountains",
    province: "British Columbia",
    country: "Canada",
    lat: 49.5,
    lng: -116.0,
    species: ["Elk", "Mule Deer", "Whitetail Deer", "Black Bear", "Grizzly Bear", "Mountain Goat"],
    pricePerDay: 700,
    rating: 4.8,
    reviewCount: 88,
    description: "British Columbia's premier multi-species outfitter. Wilderness horseback hunts in stunning mountain terrain.",
    guide: "Ryan MacLeod",
    guidePhoto: "RM",
    availability: "Aug–Nov",
    maxGuests: 6,
    featured: true,
    tags: ["Multi-Species", "Horseback", "Grizzly"],
  },
  {
    id: "9",
    name: "Deep South Hog Hunts",
    location: "Natchitoches Parish",
    province: "Louisiana",
    country: "USA",
    lat: 31.7607,
    lng: -93.0863,
    species: ["Wild Hog", "Whitetail Deer", "Turkey", "Alligator"],
    pricePerDay: 250,
    rating: 4.5,
    reviewCount: 178,
    description: "Year-round wild hog hunting with night vision equipment. Louisiana's finest whitetail and turkey hunting on 15,000 acres.",
    guide: "Jimmy Thibodaux",
    guidePhoto: "JT",
    availability: "Year-round",
    maxGuests: 10,
    featured: false,
    tags: ["Night Hunt", "Hog", "Year-Round"],
  },
  {
    id: "10",
    name: "Manitoba Trophy Moose",
    location: "The Pas Region",
    province: "Manitoba",
    country: "Canada",
    lat: 53.8,
    lng: -101.2,
    species: ["Moose", "Black Bear", "Wolf"],
    pricePerDay: 500,
    rating: 4.9,
    reviewCount: 63,
    description: "Manitoba's trophy moose country. Massive bulls, remote camps, and experienced guides for the hunt of a lifetime.",
    guide: "Frank Lévesque",
    guidePhoto: "FL",
    availability: "Sep–Oct",
    maxGuests: 4,
    featured: false,
    tags: ["Trophy", "Remote", "Moose"],
  },
];

export const ALL_SPECIES = [
  "Elk", "Mule Deer", "Whitetail Deer", "Moose", "Black Bear",
  "Brown Bear", "Grizzly Bear", "Caribou", "Bighorn Sheep", "Dall Sheep",
  "Mountain Goat", "Antelope", "Wild Hog", "Turkey", "Axis Deer",
  "Blackbuck", "Mountain Lion",
];

export const PRICE_RANGES = [
  { label: "Under $300/day", min: 0, max: 300 },
  { label: "$300–$500/day", min: 300, max: 500 },
  { label: "$500–$800/day", min: 500, max: 800 },
  { label: "$800+/day", min: 800, max: 99999 },
];
